// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: lang/parser/lang.flex

/* 14/11/2024 - Calc lexer
 * Elton M. Cardoso
 * Example of a lexer for a simple claculator language.
 *
 * This lexer implementation contains Arrays as tokens.
 * The students are encouraged to argue why this is a bad ideia !
 *
 *  Ronaldo Luiz de Freitas Santos
 *  Bernardo Lucas de Araujo Dias
 */
package lang.parser;

import java.util.ArrayList;
import java_cup.runtime.Symbol;


@SuppressWarnings("fallthrough")
public class LangLexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int ARR = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\2\1\2\0\1\1\22\0\1\1\1\2\3\0"+
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\5\20"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\2\0\1\30"+
    "\1\31\1\32\2\30\1\33\2\30\1\34\21\30\1\35"+
    "\1\36\1\37\1\0\1\40\1\0\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\43\1\47\1\50\2\43\1\51"+
    "\1\43\1\52\1\53\1\54\1\43\1\55\1\56\1\57"+
    "\1\60\5\43\1\61\1\0\1\62\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\5\24\1\25\1\26"+
    "\11\27\1\30\1\31\1\32\1\33\1\0\1\34\1\35"+
    "\1\36\1\37\1\40\4\24\3\27\1\41\5\27\3\0"+
    "\3\24\1\42\11\27\2\0\1\43\1\44\1\45\1\24"+
    "\1\46\1\47\2\27\1\50\1\27\1\51\1\27\1\52"+
    "\1\2\1\0\1\53\1\54\1\27\1\55\1\27\1\0"+
    "\1\27\1\56\1\0\1\57\5\0\1\60";

  private static int [] zzUnpackAction() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\63\0\146\0\231\0\63\0\314\0\377"+
    "\0\63\0\63\0\63\0\63\0\63\0\63\0\u0132\0\63"+
    "\0\u0165\0\u0198\0\63\0\u01cb\0\u01fe\0\u0231\0\u0264\0\u0297"+
    "\0\u02ca\0\u02fd\0\u0330\0\63\0\63\0\u0363\0\u0396\0\u03c9"+
    "\0\u03fc\0\u042f\0\u0462\0\u0495\0\u04c8\0\u04fb\0\u052e\0\63"+
    "\0\63\0\63\0\u0561\0\u0132\0\63\0\63\0\63\0\63"+
    "\0\u0594\0\u05c7\0\u05fa\0\u062d\0\u0660\0\u0693\0\u06c6\0\u0363"+
    "\0\u06f9\0\u072c\0\u075f\0\u0792\0\u07c5\0\u07f8\0\u082b\0\u085e"+
    "\0\u0891\0\u08c4\0\u08f7\0\u0264\0\u092a\0\u095d\0\u0990\0\u09c3"+
    "\0\u09f6\0\u0a29\0\u0a5c\0\u0a8f\0\u0ac2\0\u0af5\0\u0b28\0\63"+
    "\0\u0264\0\u0264\0\u0b5b\0\u0363\0\u0363\0\u0b8e\0\u0bc1\0\u0363"+
    "\0\u0bf4\0\u0363\0\u0c27\0\u0363\0\63\0\u0c5a\0\u0264\0\u0363"+
    "\0\u0c8d\0\u0363\0\u0cc0\0\u0cf3\0\u0d26\0\u0363\0\u0d59\0\u0363"+
    "\0\u0d8c\0\u0dbf\0\u0df2\0\u0e25\0\u0e58\0\63";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\5\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\3\1\35\1\3\3\36\1\37\1\40"+
    "\1\41\1\36\1\42\1\36\1\43\1\36\1\44\1\45"+
    "\1\36\1\46\1\36\1\47\1\50\64\0\1\4\107\0"+
    "\1\51\40\0\1\52\114\0\1\53\42\0\5\54\54\0"+
    "\1\54\1\0\5\21\63\0\1\55\65\0\1\56\62\0"+
    "\1\57\62\0\1\60\52\0\5\27\5\0\5\27\3\0"+
    "\21\27\20\0\5\27\5\0\5\27\3\0\13\27\1\61"+
    "\5\27\20\0\5\27\5\0\5\27\3\0\7\27\1\62"+
    "\11\27\20\0\5\27\5\0\5\27\3\0\11\27\1\63"+
    "\7\27\20\0\5\27\5\0\5\27\3\0\12\27\1\64"+
    "\6\27\20\0\5\36\5\0\5\36\3\0\21\36\20\0"+
    "\5\36\5\0\5\36\3\0\1\36\1\65\17\36\20\0"+
    "\5\36\5\0\5\36\3\0\11\36\1\66\7\36\20\0"+
    "\5\36\5\0\5\36\3\0\1\36\1\67\17\36\20\0"+
    "\5\36\5\0\5\36\3\0\6\36\1\70\10\36\1\71"+
    "\1\36\20\0\5\36\5\0\5\36\3\0\20\36\1\72"+
    "\20\0\5\36\5\0\5\36\3\0\15\36\1\73\3\36"+
    "\20\0\5\36\5\0\5\36\3\0\5\36\1\74\13\36"+
    "\20\0\5\36\5\0\5\36\3\0\15\36\1\75\3\36"+
    "\15\0\1\76\104\0\1\77\4\0\1\100\7\0\1\100"+
    "\2\0\1\100\1\0\1\100\21\0\5\27\5\0\5\27"+
    "\3\0\13\27\1\101\5\27\20\0\5\27\5\0\5\27"+
    "\3\0\1\27\1\102\17\27\20\0\5\27\5\0\5\27"+
    "\3\0\13\27\1\103\5\27\20\0\5\27\5\0\5\27"+
    "\3\0\17\27\1\104\1\27\20\0\5\36\5\0\5\36"+
    "\3\0\17\36\1\105\1\36\20\0\5\36\5\0\5\36"+
    "\3\0\16\36\1\106\2\36\20\0\5\36\5\0\5\36"+
    "\3\0\11\36\1\107\7\36\20\0\5\36\5\0\5\36"+
    "\3\0\5\36\1\110\13\36\20\0\5\36\5\0\5\36"+
    "\3\0\11\36\1\111\7\36\20\0\5\36\5\0\5\36"+
    "\3\0\10\36\1\112\10\36\20\0\5\36\5\0\5\36"+
    "\3\0\1\36\1\113\15\36\1\114\1\36\20\0\5\36"+
    "\5\0\5\36\3\0\20\36\1\115\2\0\13\76\1\116"+
    "\47\76\16\0\1\117\51\0\1\120\73\0\5\27\5\0"+
    "\5\27\3\0\11\27\1\121\7\27\20\0\5\27\5\0"+
    "\5\27\3\0\15\27\1\122\3\27\20\0\5\27\5\0"+
    "\5\27\3\0\1\27\1\123\17\27\20\0\5\36\5\0"+
    "\5\36\3\0\1\36\1\124\17\36\20\0\5\36\5\0"+
    "\5\36\3\0\5\36\1\125\13\36\20\0\5\36\5\0"+
    "\5\36\3\0\16\36\1\126\2\36\20\0\5\36\5\0"+
    "\5\36\3\0\15\36\1\127\3\36\20\0\5\36\5\0"+
    "\5\36\3\0\11\36\1\130\7\36\20\0\5\36\5\0"+
    "\5\36\3\0\12\36\1\131\6\36\20\0\5\36\5\0"+
    "\5\36\3\0\4\36\1\132\14\36\20\0\5\36\5\0"+
    "\5\36\3\0\20\36\1\133\20\0\5\36\5\0\5\36"+
    "\3\0\5\36\1\134\13\36\2\0\13\76\1\116\46\76"+
    "\1\135\13\0\1\136\65\0\5\27\5\0\5\27\3\0"+
    "\17\27\1\137\1\27\20\0\5\36\5\0\5\36\3\0"+
    "\5\36\1\140\13\36\20\0\5\36\5\0\5\36\3\0"+
    "\1\36\1\141\17\36\20\0\5\36\5\0\5\36\3\0"+
    "\17\36\1\142\1\36\20\0\5\36\5\0\5\36\3\0"+
    "\15\36\1\143\3\36\24\0\1\144\56\0\5\36\5\0"+
    "\5\36\3\0\17\36\1\145\1\36\20\0\5\36\5\0"+
    "\5\36\3\0\12\36\1\146\6\36\41\0\1\147\41\0"+
    "\5\36\5\0\5\36\3\0\5\36\1\150\13\36\63\0"+
    "\1\151\20\0\1\152\55\0\1\153\71\0\1\154\123\0"+
    "\1\155\5\0\1\156\55\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3723];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\10\1\11\2\1\1\11\2\1\6\11\1\1"+
    "\1\11\2\1\1\11\10\1\2\11\12\1\3\11\1\0"+
    "\1\1\4\11\15\1\3\0\15\1\2\0\1\11\14\1"+
    "\1\11\1\0\5\1\1\0\2\1\1\0\1\1\5\0"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
       private ArrayList<Integer> arr;

       private int toInt(String s){
          try{
              return Integer.parseInt(yytext());
          }catch(NumberFormatException e){
              System.out.println("Erro de conversão: " + s + " para inteiro");
              return 0;
          }
       }

       private float toFloat(String s){
          try{
              return Float.parseFloat(yytext());
          }catch(NumberFormatException e){
              System.out.println("Erro de conversão: " + s + " para ponto flutuante.");
              return 0;
          }
       }

       private char ascIIToChar(String s) {
           String octalValue = s.substring(2, s.length() - 1);

           try {
               int decimalValue = Integer.parseInt(octalValue, 8);
               return (char)decimalValue;
           } catch (NumberFormatException e) {
               throw new Error("Erro na conversão de valor octal (" + s + ") para ASCII.");
           }
       }

       private Symbol mkSymbol(int symCode, Object obj){
           return new Symbol(symCode, yyline + 1, yycolumn + 1, obj);
       }

       private Symbol mkSymbol(int symCode){
           return mkSymbol(symCode,null);
       }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LangLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Symbol nextToken() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {    return new Symbol(LangParserSym.EOF, yyline + 1, yycolumn + 1);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Illegal character <" + yytext() + "> at line " + (yyline + 1) + ", column " + (yycolumn + 1));
            }
          // fall through
          case 49: break;
          case 2:
            { /* N/A */
            }
          // fall through
          case 50: break;
          case 3:
            { return mkSymbol(LangParserSym.NOT);
            }
          // fall through
          case 51: break;
          case 4:
            { return mkSymbol(LangParserSym.MOD);
            }
          // fall through
          case 52: break;
          case 5:
            { return mkSymbol(LangParserSym.QUOTATION_MARKS);
            }
          // fall through
          case 53: break;
          case 6:
            { return mkSymbol(LangParserSym.OPEN_PARENTHESIS);
            }
          // fall through
          case 54: break;
          case 7:
            { return mkSymbol(LangParserSym.CLOSE_PARENTHESIS);
            }
          // fall through
          case 55: break;
          case 8:
            { return mkSymbol(LangParserSym.TIMES);
            }
          // fall through
          case 56: break;
          case 9:
            { return mkSymbol(LangParserSym.PLUS);
            }
          // fall through
          case 57: break;
          case 10:
            { return mkSymbol(LangParserSym.COMMA);
            }
          // fall through
          case 58: break;
          case 11:
            { return mkSymbol(LangParserSym.MINUS);
            }
          // fall through
          case 59: break;
          case 12:
            { return mkSymbol(LangParserSym.DOT);
            }
          // fall through
          case 60: break;
          case 13:
            { return mkSymbol(LangParserSym.DIVIDE);
            }
          // fall through
          case 61: break;
          case 14:
            { return mkSymbol(LangParserSym.INT_LITERAL, toInt(yytext()));
            }
          // fall through
          case 62: break;
          case 15:
            { return mkSymbol(LangParserSym.COLON);
            }
          // fall through
          case 63: break;
          case 16:
            { return mkSymbol(LangParserSym.SEMICOLON);
            }
          // fall through
          case 64: break;
          case 17:
            { return mkSymbol(LangParserSym.LESS);
            }
          // fall through
          case 65: break;
          case 18:
            { return mkSymbol(LangParserSym.ASSIGN);
            }
          // fall through
          case 66: break;
          case 19:
            { return mkSymbol(LangParserSym.GREATER);
            }
          // fall through
          case 67: break;
          case 20:
            { return mkSymbol(LangParserSym.TYPE_ID, yytext());
            }
          // fall through
          case 68: break;
          case 21:
            { return mkSymbol(LangParserSym.LBRACKET);
            }
          // fall through
          case 69: break;
          case 22:
            { return mkSymbol(LangParserSym.RBRACKET);
            }
          // fall through
          case 70: break;
          case 23:
            { return mkSymbol(LangParserSym.IDENTIFIER, yytext());
            }
          // fall through
          case 71: break;
          case 24:
            { return mkSymbol(LangParserSym.OPEN_BRACES);
            }
          // fall through
          case 72: break;
          case 25:
            { return mkSymbol(LangParserSym.CLOSE_BRACES);
            }
          // fall through
          case 73: break;
          case 26:
            { return mkSymbol(LangParserSym.DIFFERENT);
            }
          // fall through
          case 74: break;
          case 27:
            { return mkSymbol(LangParserSym.AND);
            }
          // fall through
          case 75: break;
          case 28:
            { return mkSymbol(LangParserSym.FLOAT_LITERAL, toFloat(yytext()));
            }
          // fall through
          case 76: break;
          case 29:
            { return mkSymbol(LangParserSym.DOUBLE_COLON);
            }
          // fall through
          case 77: break;
          case 30:
            { return mkSymbol(LangParserSym.LESS_EQUAL);
            }
          // fall through
          case 78: break;
          case 31:
            { return mkSymbol(LangParserSym.EQUAL);
            }
          // fall through
          case 79: break;
          case 32:
            { return mkSymbol(LangParserSym.GREATER_EQUAL);
            }
          // fall through
          case 80: break;
          case 33:
            { return mkSymbol(LangParserSym.IF);
            }
          // fall through
          case 81: break;
          case 34:
            { return mkSymbol(LangParserSym.INT);
            }
          // fall through
          case 82: break;
          case 35:
            { return mkSymbol(LangParserSym.ESCAPE, yytext());
            }
          // fall through
          case 83: break;
          case 36:
            { return mkSymbol(LangParserSym.BOOL);
            }
          // fall through
          case 84: break;
          case 37:
            { return mkSymbol(LangParserSym.CHAR);
            }
          // fall through
          case 85: break;
          case 38:
            { return mkSymbol(LangParserSym.DATA);
            }
          // fall through
          case 86: break;
          case 39:
            { return mkSymbol(LangParserSym.ELSE);
            }
          // fall through
          case 87: break;
          case 40:
            { return mkSymbol(LangParserSym.NULL);
            }
          // fall through
          case 88: break;
          case 41:
            { return mkSymbol(LangParserSym.READ);
            }
          // fall through
          case 89: break;
          case 42:
            { return mkSymbol(LangParserSym.TRUE, true);
            }
          // fall through
          case 90: break;
          case 43:
            { return mkSymbol(LangParserSym.FLOAT);
            }
          // fall through
          case 91: break;
          case 44:
            { return mkSymbol(LangParserSym.FALSE, false);
            }
          // fall through
          case 92: break;
          case 45:
            { return mkSymbol(LangParserSym.PRINT);
            }
          // fall through
          case 93: break;
          case 46:
            { return mkSymbol(LangParserSym.RETURN);
            }
          // fall through
          case 94: break;
          case 47:
            { return mkSymbol(LangParserSym.ITERATE);
            }
          // fall through
          case 95: break;
          case 48:
            { return mkSymbol(LangParserSym.ASCII, ascIIToChar(yytext()));
            }
          // fall through
          case 96: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
