
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lang.parser;

/** CUP generated class containing symbol constants. */
public class LangParserSym {
  /* terminals */
  public static final int LP = 4;
  public static final int NUMBER = 6;
  public static final int TRUE = 7;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int FALSE = 8;
  public static final int ID = 9;
  public static final int error = 1;
  public static final int TIMES = 3;
  public static final int RP = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "TIMES",
  "LP",
  "RP",
  "NUMBER",
  "TRUE",
  "FALSE",
  "ID"
  };
}

