
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lang.parser;

/** CUP generated class containing symbol constants. */
public class LangParserSym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int LBRACKET = 25;
  public static final int TYCHAR = 12;
  public static final int CHAR = 33;
  public static final int GREATER = 16;
  public static final int INT = 30;
  public static final int LESS = 15;
  public static final int MINUS = 3;
  public static final int DATA = 43;
  public static final int NOT = 18;
  public static final int SEMICOLON = 27;
  public static final int AND = 17;
  public static final int LP = 21;
  public static final int TYBOOL = 7;
  public static final int COMMA = 28;
  public static final int RP = 22;
  public static final int DIFFERENT = 14;
  public static final int PLUS = 2;
  public static final int IF = 37;
  public static final int ASSIGN = 20;
  public static final int ID = 32;
  public static final int EOF = 0;
  public static final int RETURN = 40;
  public static final int RBRACKET = 26;
  public static final int EQUAL = 13;
  public static final int TRUE = 34;
  public static final int error = 1;
  public static final int NULL = 36;
  public static final int TYNULL = 11;
  public static final int MOD = 6;
  public static final int TYID = 10;
  public static final int ITERATE = 39;
  public static final int TIMES = 4;
  public static final int COLON = 29;
  public static final int ELSE = 38;
  public static final int LBRACE = 23;
  public static final int READ = 41;
  public static final int TYINT = 9;
  public static final int DCOLON = 19;
  public static final int FLOAT = 31;
  public static final int RBRACE = 24;
  public static final int FALSE = 35;
  public static final int TYFLOAT = 8;
  public static final int PRINT = 42;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "TYBOOL",
  "TYFLOAT",
  "TYINT",
  "TYID",
  "TYNULL",
  "TYCHAR",
  "EQUAL",
  "DIFFERENT",
  "LESS",
  "GREATER",
  "AND",
  "NOT",
  "DCOLON",
  "ASSIGN",
  "LP",
  "RP",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "SEMICOLON",
  "COMMA",
  "COLON",
  "INT",
  "FLOAT",
  "ID",
  "CHAR",
  "TRUE",
  "FALSE",
  "NULL",
  "IF",
  "ELSE",
  "ITERATE",
  "RETURN",
  "READ",
  "PRINT",
  "DATA"
  };
}

